apiVersion: batch/v1
kind: Job
metadata:
  name: thumbnail-benchrealm1
spec:
  completions: XXX
  parallelism: XXX
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: thumbnail-compute
        image: arielszekely/thumbnail@sha256:2b966061412f6586e7b87002c33e42c0f7ae801e503bc318e7f13508da55a0a9
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 400m
            memory: 256Mi
          requests:
            cpu: 400m
            memory: 256Mi
        env:
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-creds
                key: aws-id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-creds
                key: aws-secret
          - name: AWS_DEFAULT_REGION
            value: "us-east-1"
        args:
        - "s3://9ps3/img/6.jpg 1"
      imagePullSecrets:
      - name: regcred
