apiVersion: batch/v1
kind: Job
metadata:
  name: thumbnail-benchrealm1
spec:
  completions: 100
  parallelism: 100
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: thumbnail-compute
        image: arielszekely/thumbnail@sha256:b1020fbadde54a335dbb866a35e8ed7b524abbc25f2f508daf34808e0a48ef80
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 800m
            memory: 256Mi
          requests:
            cpu: 800m
            memory: 256Mi
        env:
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-creds
                key: aws-id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-creds
                key: aws-secret
          - name: AWS_DEFAULT_REGION
            value: "us-east-1"
        args:
        - "s3://9ps3/img/6.jpg"
        - "20"
      imagePullSecrets:
      - name: regcred
