apiVersion: batch/v1
kind: Job
metadata:
  name: thumbnail-benchrealm1
spec:
  completions: 20
  parallelism: 20
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: thumbnail-compute
        image: arielszekely/thumbnail@sha256:510e1cb2d29f1f71464d34ccdeca3af46f96325a8b35136df93b5b62f5744f16
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 800m
            memory: 256Mi
          requests:
            cpu: 800m
            memory: 256Mi
        env:
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-creds
                key: aws-id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-creds
                key: aws-secret
          - name: AWS_DEFAULT_REGION
            value: "us-east-1"
        args:
        - "s3://9ps3/img/6.jpg"
        - "20"
      imagePullSecrets:
      - name: regcred
