[package]
name = "exec-uproc-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4" 
serde = { version = "1.0.188", features = ["derive"] }
serde_yaml = "0.9.25"
