apiVersion: v1
kind: ConfigMap
metadata:
  name: websrv-env-config
  namespace: default
data:
  PORT: ":8080"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websrv
spec:
  selector:
    matchLabels:
      run: websrv
  template:
    metadata:
      labels:
        run: websrv
        app: websrv
    spec:
      containers:
      - name: websrv-worker
        image: arielszekely/websrv
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1.8
          requests:
            cpu: 1.8
        ports:
          - containerPort: 8080
            name: http-websrv-svc
        envFrom:
        - configMapRef:
            name: websrv-env-config
        args:
        - "test-arg"
      imagePullSecrets:
      - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: websrv-service
spec:
  type: NodePort
  ports:
  - name: http 
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32585
  selector:
    app: websrv
