apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: websrv-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: websrv-worker
  minReplicas: 640
  maxReplicas: 640
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Pods
        value: 640
        periodSeconds: 1
